spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.81.215.217:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 333666
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 172.81.215.217:9300
      cluster-name: elasticsearch
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: 172.81.215.217
    port: 6379
logging:
  level:
    root: warn
    com.timlis: ERROR
  file: log/blog-dev.log
server:
  port: 80